### ISSUE TITLE
Deadlock in window creation with glfw 3.1 on Ubuntu 14.10 with Unity desktop

### ISSUE THREAD

**Issue by bitshifter** [bjz/glfw-rs#311]
As the title says, I'm getting a deadlock in window creation on Ubuntu 14.10 with Unity (not sure if Unity makes a difference). I've tracked this back to what appears to be a bug in glfw itself, as if I grab glfw 3.1 from git and build it I experience the same problem.

To work around this in my own project I've merged up to glfw 3.1.1 which appears to fix the problem (see https://github.com/bitshifter/glfw/tree/cargo-3.1.1).

This bug is more of an FYI, I realise servo/glfw is a separate repo from glfw-rs but it doesn't appear to have an issue tracker of it's own. I can make a pull request against servo/glfw if you think that's the best way to proceed.

The backtrace for the deadlock is:

```
#0  0x00007ffff6325830 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff6020b72 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007ffff602264f in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007ffff7add3a8 in _XReadEvents () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007ffff7ac5889 in XIfEvent () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x0000000000410554 in createWindow ()
#6  0x000000000041283f in _glfwPlatformCreateWindow ()
#7  0x000000000040a957 in glfwCreateWindow ()
#8  0x0000000000406aeb in main ()
```

**Comment by bitshifter** [comment]
I managed to track down the glfw bug https://github.com/glfw/glfw/issues/368. I've made a pull request directly to servo/glfw https://github.com/servo/glfw/pull/18 so you can probably just ignore this.
